version: '3'
services:
  backend:
    image: 'rajatsa/flaskapp'
    ports:
      - '5000:5000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb
    depends_on:
      - mysql
    networks:
      - two_tier
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DB: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      
    volumes:
      - './message.sql:/docker-entrypoint-initdb.d/message.sql'
      - 'mysql-data:/var/lib/mysql'
    networks:
      - two_tier
volumes:
  mysql-data: {}

networks:
  two_tier:
    driver: bridge
